accounts/urls.py
from django.urls import path
from  . import views

app_name = 'accounts' # Django 4.2之後加app_name
# step 1 , add path
#define the end point : index , about. Do it in views.py
urlpatterns = [
  path('signin/',views.login,name = 'login'),
  path('logout/',views.logout,name='logout'),
  path('register/',views.register,name='register'),
  path('dashboard/',views.dashboard,name='dashboard'),
]

config/urls.py
# define endpoint
# 多人用放上面
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
# 2.Django 2次分流 -> RESTFul api -> /(Resources)/Endpoint -> 分endpoint
# empty string + empty string 既分流，但無得用empty string，所以起個folder： pages
urlpatterns = [
    path('',include('pages.urls',namespace='pages')),
    path('listings/', include('listings.urls',namespace='listings')),
    path('contacts/', include('contacts.urls',namespace='contacts')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + debug_toolbar_urls() # 要同一行，隔行會error
    
admin.site.site_header = 'Clinic Administration'
admin.site.site_title = 'Clinic Admin Portal'
admin.site.index_title = 'Welcome to Clinic Portal'

listings/urls.py
from django.urls import path
from  . import views

app_name = 'listings' # Django 4.2之後加app_name

#define the end point : index , about. Do it in views.py
urlpatterns = [
  path('',views.listings,name='index'),
  path('<int:listing_id>/',views.listing,name='listing'),# int 係datatype
  path('search/',views.search,name='search'),
]

pages/urls.py
from django.urls import path
from  . import views

app_name = 'pages' # Django 4.2之後加app_name

#define the end point : index , about. Do it in views.py
urlpatterns = [
  path('',views.index,name = 'index'),
  path('about',views.about,name='about'),
  # path('listings',views.listing,name='listings'),
]

templates/partials/_alert.html
{% if messages %}
{% for message in messages%}
{% comment %} <div class="container" id="message"> {% endcomment %}
  <div class="container" class="message">
  {% comment %} <div class="alert alert-dismissible text-center alert-{{message.tags}}" role="alert"> {% endcomment %}
  <div class="alert alert-dismissible text-center alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
    <button class ="close" type="button" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
    {{message}}
    <strong><!-- expression-->
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error:{% else %} {{message.tags| title }}{% endif%}
    </strong>
  </div>
</div>
{% endfor %}
{% endif %}

templates/partials/_footer.html
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
  Copyright &copy;
  <span class="year"></span> BC Health Care
</footer>

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <div class="container">
    <!-- <a class="navbar-brand" href="index.html"> -->
    <a class="navbar-brand" href={% url 'pages:index' %}>
    <img src={% static "img/logo.png" %} class="logo" alt="" />
  </a>
    <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNavAltMarkup"
    >
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <!-- <li class="nav-item active mr-3"> -->
          <!-- hard 左active -->
          <!-- 加statement , python only-->
        {% comment %} <li {% if '/' in request.path %} class="nav-item active mr-3" {% else %} class='nav-item mr-3' {% endif %}> {% endcomment %}
        <li class="nav-item mr-3 {% if request.path == '/' %}active{% endif %}">
          <!-- <a class="nav-link" href="index.html">Home</a> -->
          <!-- pages 係跟app_name="something" -->
          <a class="nav-link" href={% url 'pages:index' %}>Home</a>
        </li>
          <!--  <li class="nav-item mr-3"> -->
          {% comment %} <!--  將 {% if '/' == request.path %} 改番做目標page:/about就做到click入個page,變active --> {% endcomment %}
        {% comment %} <li {% if '/about' in request.path %} class="nav-item active mr-3" {% else %} class='nav-item mr-3' {% endif %}> {% endcomment %}
        <li class="nav-item mr-3 {% if '/about' in request.path %}active{% endif %}">
          <a class="nav-link" href={% url 'pages:about' %}>About</a>
        </li>
        {% comment %} <li {% if '/listings' in request.path %} class="nav-item active mr-3" {% else %} class='nav-item mr-3' {% endif %}> {% endcomment %}
        <li class="nav-item mr-3 {% if 'listings' in request.path %}active{% endif %}">
          <a class="nav-link" href={% url 'listings:index' %}>
            Inpatient medical services</a
          >
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item mr-3 {% if 'dashboard' in request.path %}active{% endif %}">
          <a class="nav-link" href="{% url 'accounts:dashboard' %}">
          <i class="fas fa-user"></i> Welcome {{ user.username }}
          </a>
        </li>
        <!-- logout-->
        <li class="nav-item mr-3">
            <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link"><!-- javascript expression , Django can use -->
              <!-- click 條 a-link , 有post有token番backend-->
              <i class="fas fa-sign-out-alt" aria-hidden="true"></i>logout
            </a>

            <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
              <!-- 用form reason：backend 要delete token , 比番backend , 但_navbar.html not a pure html , 普通html唔可以咁打  -->
              {% csrf_token %}
              <input type="hidden"/> <!-- 收埋input，變hidden-->
            </form>
        </li>

        {% else %}
          <li {% if 'register' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}> 
            <a class="nav-link" href="{% url 'accounts:register' %}">
            <i class="fas fa-user-plus"></i> Register
            </a>
          </li>
          <li {% if 'login' in request.path %} class="nav-item active mr-3" {% else %} class='nav-item mr-3' {% endif %}> 
            <a class="nav-link" href="{% url 'accounts:login'%}">
            <i class="fas fa-sign-in-alt"></i>Login</a
          >
          </li>

          {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/partials/_search_form.html
<section id="showcase">
  <div class="container text-center">
    <div class="home-search p-5">
      <div class="overlay p-5">
        <h1 class="display-4 mb-4">Clinic Search</h1>
        <div class="search">
          <form action="{% url 'listings:search' %}">
            <div class="form-row">
              <div class="col-md-12 mb-3">
                <input
                  type="text"
                  name="keywords"
                  class="form-control"
                  placeholder="Keyword (Clinic, Doctor, etc)"
                  value="{{ values.keywords}}"
                />
              </div>
            </div>

            <div class="form-row">
              <div class="col-md-4 mb-3">
                <select name="district" class="form-control">
                  {% comment %} <option selected="true" disabled="disabled"> {% endcomment %}
                  <option {% if not values.district %}selected="true" value="" {% endif%}> <!-- 如果無選擇>>empty value>>Not True>>著左做True>>出value="" -->
                    District (All)
                  </option>
                  {% comment %} {% for key, value in  %}
                  <option value="{{ key }}" {% if key == values.district %} selected = "true" {% endif %}>
                  {{ value }}
                  </option>
                  {% endfor %}
                </select> {% endcomment %}
                {% for region,districts in district_groups_choices %}
                <optgroup label="{{region}}"> 
                  {% for key,value in districts %}
                  {% comment %} <option value="{{value}}" {%if value == values.district%} selected = "true" {%endif%}>
                    {{value}}
                  </option> {% endcomment %}
                  <option value="{{value}}" {%if value == values.district%} selected = "true" {%endif%}>
                    {{ value }}
                  </option>
                  {% endfor%}
                </optgroup>
                {%endfor%}
              </select>
            </div>

              <div class="col-md-4 mb-3">
                <select name="rooms" class="form-control">
                  {% comment %} <option selected="true" disabled="disabled"> {% endcomment %}
                  <option {% if not values.rooms %}selected="true" value="" {% endif%}> <!--Result : 出番Rooms (All)-->
                    Rooms (All)
                  </option>
                  {% for key, value in bedroom_choices.items %}
                  <option value="{{ key }}"
                    {% if key == values.rooms %} selected {% endif%}>
                    {{ value }}
                  </option>
                  {% endfor %}
                </select>
              </div>

              <div class="col-md-4 mb-3">
                <select name="room_type" class="form-control">
                  {% comment %} <option selected="true" disabled="disabled"> {% endcomment %}
                  <option {% if not values.room_type %}selected="true" value="" {% endif%}>
                    Room Type (All)
                  </option>
                  {% for key, value in room_type_choices.items %}
                  <option value="{{ key }}"
                    {% if key == values.room_type %}selected{% endif%}> {{value}}
                  </option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">
              Submit form
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

templates/partials/_topbar.html
<section id="top-bar" class="p-3">
  <div class="container">
    <div class="row">
      <div class="col-md-4"><i class="fas fa-phone"></i> (852)-555-5555</div>
      <div class="col-md-4">
        <i class="fas fa-envelope-open"></i> contact@healthcare.co
      </div>
      <div class="col-md-4">
        <div class="social text-right">
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
          <!-- you can add external link to replace # -->
          <a href="#">
            <i class="fab fa-facebook"></i>
          </a>
          <a href="#">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="#">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="#">
            <i class="fab fa-pinterest"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>