accounts/urls.py
from django.urls import path
from  . import views

app_name = 'accounts' # Django 4.2之後加app_name
# step 1 , add path
#define the end point : index , about. Do it in views.py
urlpatterns = [
  path('signin/',views.login,name = 'login'),
  path('logout/',views.logout,name='logout'),
  path('register/',views.register,name='register'),
  path('dashboard/',views.dashboard,name='dashboard'),
]

config/urls.py
# define endpoint
# 多人用放上面
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
# 2.Django 2次分流 -> RESTFul api -> /(Resources)/Endpoint -> 分endpoint
# empty string + empty string 既分流，但無得用empty string，所以起個folder： pages
urlpatterns = [
    path('',include('pages.urls',namespace='pages')),
    path('listings/', include('listings.urls',namespace='listings')),
    path('contacts/', include('contacts.urls',namespace='contacts')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + debug_toolbar_urls() # 要同一行，隔行會error
    
admin.site.site_header = 'Clinic Administration'
admin.site.site_title = 'Clinic Admin Portal'
admin.site.index_title = 'Welcome to Clinic Portal'

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'  

urlpatterns = [
    path('contact', views.contacts, name='contact'),
    path('contact/delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('contact/edit/<int:contact_id>', views.edit_contact, name='edit_contact'),
]

listings/urls.py
from django.urls import path
from  . import views

app_name = 'listings' # Django 4.2之後加app_name

#define the end point : index , about. Do it in views.py
urlpatterns = [
  path('',views.listings,name='index'),
  path('<int:listing_id>/',views.listing,name='listing'),# int 係datatype
  path('search/',views.search,name='search'),
]

pages/urls.py
from django.urls import path
from  . import views

app_name = 'pages' # Django 4.2之後加app_name

#define the end point : index , about. Do it in views.py
urlpatterns = [
  path('',views.index,name = 'index'),
  path('about',views.about,name='about'),
  # path('listings',views.listing,name='listings'),
]

accounts/models.py
from django.db import models

# Create your models here.
class account(models.Model):
  name = models.CharField(max_length=20)
  password = models.CharField()

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.models import User
from contacts.models import Contact
# Create your views here.
# step 2 , define function
def login(request):
  if request.method == 'POST':
    username = request.POST.get('username') # ['username']
    # password = request.POST['password']
    password = request.POST.get('password')
    user = auth.authenticate(username=username,password=password)
    if user is not None:
      auth.login(request,user)
      messages.success(request,'You are now logged in.')
      return redirect('accounts:dashboard')
    else:
      messages.error(request,'Invalid credentials')
      return redirect('accounts:login') # redirect to endpoint, don't add .html, render requires .html
  else:
    return render(request,'accounts/login.html')

def logout(request):
  if request.method=="POST":
    auth.logout(request)
    messages.success(request,'You are now logged out.')
    return redirect('pages:index')
  return redirect('pages:index')   

def register(request):
  if request.method == 'POST':
    # handle registration logic here
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    password2 = request.POST['password2']
    if password == password2:
      if User.objects.filter(username=username).exists():
        messages.error(request,"Username already exists.")
        return redirect("accounts:register")
      else:
        if User.objects.filter(email=email).exists():
          messages.error(request,"Email already exists.")
          return redirect("accounts:register")
        else:
          user = User.objects.create_user(username=username,password=password,email=email,first_name=first_name,last_name=last_name)
          user.save()
          messages.success(request,'You are now registered and can login.')
          return redirect("accounts:login")
    else:
      messages.error(request,'Passwords do not match')
      return redirect("accounts:register")
  else:
    return render(request,'accounts/register.html')

def dashboard(request):
  # 一定login左，exist user， Contact searching database
  # 點解係accounts/views.py, not contacts/views.py?
  # Welcome {{user.first_name}} 係come from accounts/views.py
  user_contacts = Contact.objects.all().filter(user_id=request.user.id).order_by('-contact_date')
  # all()加唔加都得
  context = {"contacts": user_contacts}
  return render(request,'accounts/dashboard.html',context)

# 一次分流分app
# 二次分流分endpoint
# 要做晒諗晒有幾多個endpoint先做

templates/accounts/dashboard.html
{% extends 'base.html' %}
<!-- load base-->
{% load humanize %}
<!-- load humanize-->
{% comment %} {% load static %} {% endcomment %}
<!-- block title-->
{% block title %} | {{user.username}}  {% endblock %}
<!--load static -->
{% block content %}

  {% comment %} <body> {% endcomment %}
    <section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">User Dashboard</h1>
            <p class="lead">Manage your BC Health Care account</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb --> 
    <section id="bc" class="mt-3">
      <div class="container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              {% comment %} a-link is MVT - view {% endcomment %}
              <a href="{% url 'pages:index'%}"> 
                <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active">Dashboard</li>
          </ol>
        </nav>
      </div>
    </section>

    <!-- Listing 1 -->
    {% comment %} {% if accounts %} {% endcomment %}
    <!-- for loop accounts -->
    {% comment %} {% for account in accounts %} {% endcomment %}
    {% include 'partials/_alert.html' %}
    <section id="dashboard" class="py-4">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            {% comment %} <h2>Welcome {{ account.name  | title }}</h2> {% endcomment %}
            <h2>Welcome {{ user.username  | title }}</h2>
            <!-- add for-loop @ 6/1/2026-->
            {% if contacts%}
            <p>Here are the clinic listings that you have inquired about</p>
            <table class="table"> <!-- table : must have head，body -->
              <thead>
                <tr>
                  <th scope="col">Clinic ID</th>
                  <th scope="col">Clinic</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% comment %} for loop listing  {% endcomment %}
                {% for contact in contacts %}
                <tr>
                  <td>{{contact.listing_id}}</td>
                  <td>{{ contact.listing | title}}</td>
                  <td>
                    <a class="btn btn-light" href="{% url 'listings:listing' contact.listing_id %}">View Listing</a>
                    <button class="btn btn-danger" 
                    data-url="{% url 'contacts:delete_contact' contact.id %}"
                    {% comment %} delete完要confirm {% endcomment %}
                    data-toggle="modal" 
                    {% comment %} data-toggle = On/Off function {% endcomment %}
                    data-target="#deleteConfirmModal"
                    data-id="{{contact.id}}"
                    {% comment %} data-id 既contact.id入份去data-url {% endcomment %}
                    >Delete Listing</button>
                    <a href ="{% url 'contacts:edit_contact' contact.id%}" 
                    class="btn btn-success"
                    >Edit Message</a>
                    {% comment %} 用Django form黎做edit_contact {% endcomment %}
                    
                  </td>
                  {% comment %} data:create一個data value, internal variable,帶住value去番backend {% endcomment %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% else %}
            <p>You have not made any inquiries yet.</p>
            {% endif %}
          </div>
        </div>
      </div>
    </section>
    <!-- Delete Modal -->
    <!-- define dialog box-->
      <div
      class="modal fade"
      id="deleteConfirmModal"
      role="dialog">
      <!-- 畫線 -->
        <div class="modal-dialog">
          <!-- define area -->
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" 
              id="deleteModalLabel"
              >Confirm DELETE</h5>
              <!-- 出個交叉-->
              <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this inquiry?</p>
            {% comment %} if onClick Yes , will show a box to show confirmDeleteBtn {% endcomment %}
            {% comment %} then Yes will back to data-url {% endcomment %}
            <a href="" class="btn btn-danger" id="confirmDeleteBtn">Yes</a>
            {% comment %} 呢度href 係冇野，因為要靠data-url 去放條URL入黎 {% endcomment %}
            <button class="btn btn-info" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    {% endblock content%}
    {% comment %} {% endfor %}{% endif %} {% endcomment %}
  {% comment %} </body> {% endcomment %}

templates/accounts/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
<!-- load base-->
{% load humanize %}
<!-- load humanize-->
{% load static %}
<!-- block title-->
{% block title %} | Login {% endblock %}
<!--load static -->
{% block content %}
<body>
    <section id="login" class="bg-light py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% include 'partials/_alert.html'%} <!-- show Bootstrap Alerts 既關鍵-->
            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-sign-in-alt"></i> Login</h4>
              </div>
              <div class="card-body">
                <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>

                  <div class="form-group">
                    <label for="password">Password</label>
                    <input
                      type="password"
                      name="password"
                      class="form-control"
                      required
                    />
                  </div>

                  <input
                    type="submit"
                    value="Login"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
<!-- load humanize-->
{% load humanize %}
<!-- block title-->
{% block title %} | Register {% endblock %}
<!--load static -->
{% block content %}
    <section id="register" class="bg-light py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% include 'partials/_alert.html'%}
            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-user-plus"></i> Register</h4>
              </div>
              <div class="card-body">
                <form action="{% url 'accounts:register' %}" method = 'POST'>
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input
                      id="first_name"
                      type="text"
                      name="first_name"
                      class="form-control"
                      
                    />
                  </div>
                  <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input
                      id="last_name"
                      type="text"
                      name="last_name"
                      class="form-control"
                      
                    />
                  </div>
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input
                      id="email"
                      type="email"
                      name="email"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input
                      id="password"
                      type="password"
                      name="password"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="password2">Confirm Password</label><!-- for 係乜，id就比乜-->
                    <input
                      id="password2"
                      type="password"
                      name="password2"
                      class="form-control"
                      required
                    />
                  </div>
                  <input
                    type="submit"
                    value="Register"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}