config/urls.py
# define endpoint
# 多人用放上面
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
# 2.Django 2次分流 -> RESTFul api -> /(Resources)/Endpoint -> 分endpoint
# empty string + empty string 既分流，但無得用empty string，所以起個folder： pages
urlpatterns = [
    path('',include('pages.urls',namespace='pages')),
    path('listings/', include('listings.urls',namespace='listings')),
    path('contacts/', include('contacts.urls',namespace='contacts')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + debug_toolbar_urls() # 要同一行，隔行會error
    
admin.site.site_header = 'Clinic Administration'
admin.site.site_title = 'Clinic Admin Portal'
admin.site.index_title = 'Welcome to Clinic Portal'

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'  

urlpatterns = [
    path('contact', views.contacts, name='contact'),
    path('contact/delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('contact/edit/<int:contact_id>', views.edit_contact, name='edit_contact'),
]

listings/urls.py
from django.urls import path
from  . import views

app_name = 'listings' # Django 4.2之後加app_name

#define the end point : index , about. Do it in views.py
urlpatterns = [
  path('',views.listings,name='index'),
  path('<int:listing_id>/',views.listing,name='listing'),# int 係datatype
  path('search/',views.search,name='search'),
]

pages/urls.py
from django.urls import path
from  . import views

app_name = 'pages' # Django 4.2之後加app_name

#define the end point : index , about. Do it in views.py
urlpatterns = [
  path('',views.index,name = 'index'),
  path('about',views.about,name='about'),
  # path('listings',views.listing,name='listings'),
]

listings/models.py
from django.db import models
from doctors.models import Doctor
from .choices import district_groups_choices,room_type_choices,bedroom_choices
from taggit.managers import TaggableManager

# Create your models here.
class Subject(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
          return self.name

class Listing(models.Model):
  doctor = models.ForeignKey(Doctor,on_delete= models.DO_NOTHING)
  title = models.CharField(max_length=200)
  address = models.CharField(max_length=200)
  district = models.CharField(max_length=50,choices=district_groups_choices)# 輔助性，唔洗'make makemigrations'
  description = models.TextField(blank=True)
  # services = models.TextField(blank=True)
  services = TaggableManager(verbose_name="Services")
  service = models.IntegerField()
  room_type = models.CharField(max_length=200,default='',choices=room_type_choices.items())
  rooms = models.CharField(max_length=2,choices=bedroom_choices.items())
  # profession = models.CharField(max_length=200,default='')
  profession = models.ManyToManyField(Subject,blank=True)
  photo_main = models.ImageField(upload_to = 'photos/%Y/%d',blank=True)
  photo_1 = models.ImageField(upload_to = 'photos/%Y/%d',blank=True)
  photo_2 = models.ImageField(upload_to = 'photos/%Y/%d',blank=True)
  photo_3 = models.ImageField(upload_to = 'photos/%Y/%d',blank=True)
  photo_4 = models.ImageField(upload_to = 'photos/%Y/%d',blank=True)
  is_published = models.BooleanField(default=True)
  list_date = models.DateTimeField(auto_now_add=True)
  def __str__(self):
    return self.title
  
  def tag_list(self):
    # return u", ".join(tag.name.replace(" ","-") for tag in self.services.all())
    return u", ".join(tag.slug for tag in self.services.all())

  class Meta:
    ordering = ['-list_date']
    indexes = [models.Index(fields = ['list_date'])]

    def __str__(self):
        return self.title

listings/views.py
from django.shortcuts import render,get_object_or_404
from listings.models import Listing
from django.core.paginator import Paginator
from django.db.models import Q
from listings.choices import district_groups_choices,bedroom_choices,room_type_choices
# Create your views here.
# 3.最終分黎呢度，2個endpoint
def listings(request):
  # print(request.path) # /listings/
  listings = Listing.objects.filter(is_published=True)
  paginator = Paginator(listings,3)
  page = request.GET.get('page')
  paged_listings = paginator.get_page(page)
  content = {'listings':paged_listings}
  return render(request,'listings/listings.html',content)
# ('pages/index.html')

def listing(request,listing_id):
  # return HttpResponse('<h1>about</h1>')
  listing = get_object_or_404(Listing,pk=listing_id)
  content = {'listing':listing}
  return render(request,'listings/listing.html',content)

def search(request):
  # get all data
  queryset_list = Listing.objects.order_by('-list_date').filter(is_published=True)

  # sorted_district_groups = {}
  # for region , districts in district_groups_choices.items():
  #   sorted_district_groups[region] = sorted(districts.items(),key = lambda x:x[1])
  # filter keywords
  if 'keywords' in request.GET:
    keywords = request.GET['keywords']
    if keywords:
      # queryset_list = queryset_list.filter(title__icontains=keywords)
      queryset_list = queryset_list.filter(
                Q(title__icontains=keywords) | 
                Q(description__icontains=keywords)|
                Q(doctor__name__icontains=keywords) # use double '_' to connect doctor and name
            )
  # filter district
  if 'district' in request.GET:
    district = request.GET['district']
    if district:
      queryset_list = queryset_list.filter(district__iexact=district)

  # filter room
  if 'rooms' in request.GET:
    rooms = request.GET['rooms']
    if rooms:
      queryset_list = queryset_list.filter(rooms=rooms)

  # filter roomtype
  if 'room_type' in request.GET:
    room_type = request.GET['room_type']
    if room_type:
      queryset_list = queryset_list.filter(room_type__iexact=room_type)

  paginator = Paginator(queryset_list,3)
  page = request.GET.get('page')
  page_listings = paginator.get_page(page)

  context = {
        'listings':page_listings,
        'district_groups_choices': district_groups_choices,
        'bedroom_choices': bedroom_choices,
        'room_type_choices': room_type_choices,
        # 'listings':queryset_list,
        'values':request.GET
    }
  return render(request,'listings/search.html',context)

templates/listings/listing.html
{% extends 'base.html' %}
<!-- load base-->
{% load humanize %}
<!-- load humanize-->
{% load static %}
<!-- block title-->
{% block title %} | {{listing.title | title}} {% endblock %}
<!-- block content-->
{% block content %}

<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">{{listing.title|title}}</h1>
        <p class="lead">
          <i class="fas fa-map-marker"></i> {{listing.district |title}}
        </p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:index' %}">Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'listings:index' %}">Listings</a>
        </li>
        <li class="breadcrumb-item active">{{listing.title|title}}</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Listing -->
<section id="listing" class="py-4">
  <div class="container">
    <a href="{% url 'listings:index' %}" class="btn btn-light mb-4"
      >Back To Listings</a
    >
    <div class="row">
      <div class="col-md-9">
        <!-- Home Main Image -->
        <img
          src="{{ listing.photo_main.url}}"
          alt=""
          class="img-main img-fluid mb-3"
        />
        <!-- Thumbnails -->
        <div class="row mb-5 thumbs">
          <div class="col-md-3">
            {% comment %} {% is listing.photo_main %}
            <a href="{{ listing.photo_main.url }}" data-lightbox="home-images">
              <img
                src="{{ listing.photo_main.url }}"
                alt=""
                class="img-fluid"
              />
            </a>
          </div>
          {% endif %} {% endcomment %}
          {% if listing.photo_1 %}
          <div class="col-md-2">
            <a href="{{ listing.photo_1.url }}" data-lightbox="home-images">
              <img src="{{ listing.photo_1.url }}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %} {% if listing.photo_2 %}
          <div class="col-md-2">
            <a href="{{ listing.photo_2.url }}" data-lightbox="home-images">
              <img src="{{listing.photo_2.url}}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %} {% if listing.photo_3 %}
          <div class="col-md-2">
            <a href="{{ listing.photo_3.url }}" data-lightbox="home-images">
              <img src="{{listing.photo_3.url}}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %} {% if listing.photo_4 %}
          <div class="col-md-2">
            <a href="{{ listing.photo_4.url }}" data-lightbox="home-images">
              <img src="{{listing.photo_4.url}}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %}
        </div>

        <!-- Fields -->
        <div class="row mb-5 fields">
          <div class="col-md-12">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-secondary">
                <i class="fas fa-money-bill-alt"></i> {{listing.title|title}} Fee Estimate:
                <span class="float-right"
                  >$ {{listing.service | intcomma | capfirst}} /Day</span
                >
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bed"></i> Rooms:
                <span class="float-right"> {{listing.rooms}} </span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bed"></i> Room Type:
                <span class="float-right">{{listing.room_type}}</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bath"></i> Services:
                <span class="float-right">{{listing.services}}</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-dumbbell"></i> Profession:
                <span class="float-right"> {{listing.profession}} </span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-dumbbell"></i> Address:
                <span class="float-right"> {{listing.address}} </span>
              </li>
            </ul>
          </div>
        </div>
        {% comment %} 07/01/2026 , 加tag show profession {% endcomment %}

        <!-- profession -->
        <div>
        <div class="row mb-5">
            {% comment %} h4.mr-3.text-secondary{Professions:} {% endcomment %}
          {% comment %} <div class="col-md-4 d-flex align-items-start"> {% endcomment %}
          <h4 class="mr-3 text-secondary">Professions:</h4>
          {% if listing.profession.all %}
            <ul>
              {% for profession in listing.profession.all %}
              <li class="mr-3">
                <h4>{{profession.name}}</h4>
              </li>
              {% endfor %}
            </ul>
          {% comment %} follow listings/models.py field name {% endcomment %}
          {% else %}
            <p class="text-secondary">No Professions Listed</p>
          {% endif %}
        </div>
        {% comment %} </div> {% endcomment %}

        <!-- Services -->
        <div class="row mb-5">
          <h4 class="mr-3 text-secondary">Services :</h4>
          {% if listings.services.all %}
          <!-- service tag-->
          <ul>
            {% for service in listings.services.all %}
            <li class="mr-3"><h4>{{service.name | title}}</h4></li>
            {% endfor %}
          </ul>
          {% else %}
          <h4>No Services</h4>
          {% endif %}
        </div>
      </div>

        <!-- Description -->
        <div class="row mb-5 text-center">
          <div class="col-md-12">
            <h5 class="text-primary">{{listing.description|linebreaks}}</h5>
            <p>{{ listing.description }}</p>
          </div>
        </div>
      </div>
      <!-- Make Inquiry -->
      <div class="col-md-3">
        <div class="card mb-3">
          <img
            class="card-img-top"
            src="{{listing.doctor.photo.url}}"
            alt="Seller of the month"
          />
          <div class="card-body">
            <h5 class="card-title">Medical Practitioner</h5>
            <h6 class="text-secondary">{{listing.doctor.name}}</h6>
          </div>
        </div>
        <button
          class="btn-primary btn-block btn-lg"
          data-toggle="modal"
          data-target="#inquiryModal"
        >
          Make An Inquiry
        </button>
      </div>
    </div>
  </div>
</section>

<!-- Inquiry Modal -->
<div class="modal fade" id="inquiryModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{% url 'contacts:contact' %}">
          {% csrf_token %}
          <input type="hidden" name="doctor_email" value="{{ listing.doctor.email }}">
          <input type="hidden" name="listing_id" value="{{listing.id}}" />
          <input 
          type="hidden" 
          class="doctor_email"
          value="{{listing.doctor.email}}"/>
          {% if user.is_authenticated %}
          <!-- start of take care input form -->
            <input type="hidden" name="user_id" value="{{ user.id }}">
          {% else %}
            <input type="hidden" name="0"/>
          {% endif%}
          <!-- end of take care input form -->
        {% comment %} <input type="hidden" name="listing_id" value="{{listing.id}}" /> {% endcomment %}
          <div class="form-group">
            <label for="listing" class="col-form-label">Clinic:</label>
            <input
              type="text"
              name="listing"
              class="form-control"
              value="{{listing.title | title }}"
              readonly 
              {% comment %} readonly, 等人唔要modify data 同 data 入name="listing" {% endcomment %}
              {% comment %} disabled , 唔入database,backend 會emptyString {% endcomment %}
            />
          </div>
          <div class="form-group">
            <label for="name" class="col-form-label">Name:</label>
            <input type="text" name="name" class="form-control" {% if user.is_authenticated %} value="{{user.first_name}} {{user.last_name}}" readonly {% endif %} />
          </div>
          <div class="form-group">
            <label for="email" class="col-form-label">Email:</label>
            <input type="email" name="email" class="form-control" {% if user.is_authenticated %} value="{{user.email}}" readonly {% endif %} />
          </div>
          <div class="form-group">
            <label for="phone" class="col-form-label">Phone:</label>
            <input type="text" name="phone" class="form-control" required />
          </div>
          <div class="form-group">
            <label for="message" class="col-form-label">Message:</label>
            <textarea name="message" class="form-control"></textarea>
          </div>
          <hr />
          <input
            type="submit"
            value="Send"
            class="btn btn-block btn-secondary"
          />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/listings/listings.html
{% extends 'base.html' %}
<!-- load base-->
{% load humanize %}
<!-- load humanize-->
{% load static %}
<!-- block title-->
{% block title %} | Browser Listings {% endblock %}
<!--load static -->
{% block content %}
    <section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">Browse Our Clinic</h1>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
              pariatur!
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              {% comment %} 去個home，所以pages，not listings {% endcomment %}
              <a href={% url 'pages:index'%}><i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active">Browse Listings</li>
          </ol>
        </nav>
      </div>
    </section>
    <!-- Listings -->
    <section id="listings" class="py-4">
  <div class="container">
    <div class="row">
      {% if listings %}
        {% for listing in listings %}
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
              <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="" />
              <div class="card-img-overlay"></div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">{{ listing.title | title }}</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i>
                    {{listing.district | title}}
                  </p>
                </div>

                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i>
                    Services {{listing.service|apnumber | capfirst}}
                  </div>
                  <div class="col-6"><i class="fas fa-dumbbell"></i> Treatment</div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> rooms {{listing.rooms}}
                  </div>
                  <div class="col-6"><i class="fas fa-bath"></i> Bathrooms</div>
                </div>

                <div class="row py-2 text-secondary">
                  <div class="col-12">
                    <i class="fas fa-user"></i> {{listing.doctor.name}}
                  </div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-12">
                    <i class="fas fa-clock"></i> {{listing.list_date | timesince}}
                  </div>
                </div>

                <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">
                  More Info
                </a>
              </div>
            </div>
          </div> 
        {% endfor %} 
        {% endif %}
    </div> <div class="row">
      <div class="col-md-12">
        {% if listings.has_other_pages %}
        <ul class="pagination">
          {% if listings.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ listings.previous_page_number }}">&laquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link">&laquo;</a>
            </li>
          {% endif %}

          {% for i in listings.paginator.page_range %}
            {% if listings.number == i %}
              <li class="page-item active">
                <a class="page-link">{{i}}</a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{i}}">{{i}}</a>
              </li>
            {% endif %}
          {% endfor %}

          {% if listings.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ listings.next_page_number }}">&raquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link">&raquo;</a>
            </li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
    </div>
    
  </div> </section>
{% endblock %}

{% comment %} <!-- {% extends 'base.html' %}必須放檔案最頂部，extends關係 --> {% endcomment %}
{% comment %} <!-- {% load static %}，會拎static既野用：static picture，CSS(base.html打完呢句，都要係child class用) --> {% endcomment %}
{% comment %} <!-- {% block content %} 與 {% endblock %}：挖窿同填窿 --> {% endcomment %}

templates/listings/search.html
{% extends 'base.html' %}
<!-- load humanize -->
{% load humanize%}
<!-- load static -->
{% load static%}
<!-- tab title-->
{% block title %} | Search {% endblock %}
<!-- index main content-->
{% block content %}
<!-- search_form -->
{% include 'partials/_search_form.html' %}

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html"> <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="listings.html">Browse Listings</a>
        </li>
        <li class="breadcrumb-item active">Search Results</li>
      </ol>
    </nav>
  </div>
</section>

<section id="listings" class="py-4">
  <div class="container">
    <div class="row">
      {% if listings %}
      <!-- for loop -->
      {% for listing in listings %}
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card listing-preview">
          <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="" />
          <div class="card-body">
            <div class="listing-heading text-center">
              <h4 class="text-primary">{{ listing.title | title}}</h4>
              <p>
                <i class="fas fa-map-marker text-secondary"></i>
                {{ listing.district }}
              </p>
            </div>
            <hr />
            <a
              href="{% url 'listings:listing' listing.id %}"
              class="btn btn-primary btn-block"
              >More Info</a
            >
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <div class="col-md-12">
        <p>No Results Found.</p>
      </div>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}